//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ColorEnhansement.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_COLORETYPE                  129
#define IDD_DIALOG1                     130
#define IDD_HISTOGRAMDISPLAY            131
#define IDC_EDIT1                       1000
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT2                       1007
#define IDC_HISTOGRAM                   1014
#define IDC_HISTOGRAMDIS                1015
#define ID_ENHAN                        32771
#define ID_EN                           32772
#define ID_DISPLAYHISTOGRAM             32773
#define DISPLAY_TRANSFORM               32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
